import React from "react";
import {
	Activity,
	AlertCircle,
	CheckCircle2,
	Clock,
	Database,
	FileCheck,
	FileText,
	Gauge,
	HardDrive,
	HelpCircle,
	LifeBuoy,
	Map,
	RefreshCw,
	Settings,
	Terminal,
	Upload,
	Zap,
	BarChart2,
} from "lucide-react";

const commonSubmitValidation = {
	submitButton: {
		id: "submitForm",
		text: "Submit",
		type: "button",
		position: "bottom",
		buttonStyle: "primary",
		validation: {
			enabled: true,
			errorMessage: "Please fill in all required fields marked with *",
			errorStyle: "text-red-600 font-medium mt-2",
		},
	},
};

// Health Check Schema
export const healthCheckSchema = {
	sectionName: "healthcheck",
	sectionTitle: "Health Check",
	sectionIcon: "Activity",
	sectionColor: "blue",
	sectionDescription: "Routine tasks performed to ensure the NF is healthy.",
	questions: [
		{
			id: "hasMOPs",
			text: "Does your NF have MOPs available for performing health checks? If so, please upload the MOPs in the next question. These can be vendor-provided and/or replace-created MOPs.",
			required: true,
			type: "radio",
			cardTitle: "MOP Availability",
			cardIcon: "FileCheck",
			options: [
				{ value: "yes", label: "Yes" },
				{ value: "no", label: "No" },
			],
			conditionalQuestions: {
				yes: ["uploadMOPs"],
			},
		},
		{
			id: "undocumentedSteps",
			text: "Do you have any health check steps that are performed that are not part of any MOPs? If so, please provide the list of steps with details - actions being performed,  how they are performed, and the expected results; along with any remediation procedures if the health checks fail.",
			required: false,
			cardTitle: "MOP Availability",
			cardIcon: "Terminal",
			type: "textarea",
			placeholder: "Your steps here:",
			rows: 4,
		},
		{
			id: "uploadMOPs",
			text: "Please upload your MOPs.",
			required: true,
			type: "file",
			maxFiles: 10,
			maxSingleFileSizeInMB: 30,
			maxUploadSizeInMB: 300,
			acceptedFormats: ["pdf", "docx", "xlsx"],
			hidden: true,
		},
		{
			id: "stepsCount",
			text: "How many steps are involved in the health check?",
			required: true,
			type: "number",
			cardTitle: "Process Details",
			cardIcon: "Clock",
			placeholder: "Enter number of steps",
			description:
				"Enter the total number of discrete steps in the health check process",
			icon: "Activity",
			unit: "steps",
		},
		{
			id: "frequencyCheck",
			text: "What should be the frequency for health checks?",
			required: true,
			cardTitle: "Process Details",
			cardIcon: "Terminal",
			type: "textarea",
			placeholder: "Please specify the exact day and time. \nExample: Daily at 11:00 PM ET to avoid maintenance windows and peak usage hours.",
			rows: 4,
		},
		{
			id: "hasAutomation",
			text: "Has any automation been developed for performing health checks?",
			required: true,
			type: "radio",
			cardTitle: "Automation Status",
			cardIcon: "Terminal",
			options: [
				{
					value: "yes",
					label: "Yes",
					description: "Fully automated",
					color: "green",
				},
				{
					value: "partial",
					label: "Partial",
					description: "Some steps automated",
					color: "blue",
				},
				{
					value: "no",
					label: "No",
					description: "Completely manual",
					color: "red",
				},
			],
			conditionalQuestions: {
				yes: [
					"minutesCount",
					"automationLinks",
					"uploadAutomationDocs",
					"automatedStepsCount",
					"automationPayload",
					"validationMechanisms",
				],
				partial: [
					"automationLinks",
					"uploadAutomationDocs",
					"automatedStepsCount",
					"validationMechanisms",
				],
			},
		},
		{
			id: "minutesCount",
			text: "How many minutes does it take to complete the automated process?",
			required: false,
			type: "number",
			placeholder: "Enter time",
			description:
				"Average time to complete all health check steps using automation",
			icon: "Clock",
			unit: "minutes",
			hidden: true,
		},
		{
			id: "automationLinks",
			text: "Please provide the links to the automations in comma seperated format",
			required: true,
			type: "textarea",
			placeholder: "e.g GIT or ATLAS or Google Drive",
			rows: 2,
			hidden: true,
		},
		{
			id: "uploadAutomationDocs",
			text: "If you have a separate MOP for automation, please upload it here.",
			required: false,
			type: "file",
			maxFiles: 10,
			maxSingleFileSizeInMB: 30,
			maxUploadSizeInMB: 300,
			acceptedFormats: ["pdf", "docx", "xlsx"],
			hidden: true,
		},
		{
			id: "automatedStepsCount",
			text: "Please provide the total number of steps that are automated.",
			required: true,
			type: "number",
			icon: "Activity",
			unit: "steps",
			placeholder: "# of Steps",
			rows: 2,
			hidden: true,
		},
		{
			id: "automationPayload",
			text: "Is there automation to generate payloads required for above automations?",
			required: false,
			type: "radio",
			options: [
				{ value: "yes", label: "Yes" },
				{ value: "no", label: "No" },
			],
			hidden: true,
		},
		{
			id: "validationMechanisms",
			text: "What mechanisms do you use to determine whether the health check steps were successful or failed?",
			required: true,
			type: "checkbox",
			options: [
				{ value: "health-checks", label: "Automated Health Checks" },
				{ value: "service-status", label: "Service Status Checks" },
				{ value: "database", label: "Database Validation" },
				{ value: "e2e", label: "E2E Testing" },
				{ value: "dashboards", label: "Monitoring Dashboards" },
				{ value: "logs", label: "Log Analysis" },
				{ value: "other", label: "Other" },
			],
			conditionalQuestions: {
				other: ["otherMechanism"],
			},
			hidden: true,
		},
		{
			id: "otherMechanism",
			text: "Please specify other mechanisms",
			required: true,
			type: "text",
			placeholder: "Please specify other mechanisms",
			hidden: true,
		},
		{
			id: "kpis",
			text: "What are the key performance indicators (KPIs) used to determine that the NF is functioning normally ? Please specify the names of the KPIs along with the nominal ranges that are considered normal.",
			required: false,
			type: "textarea",
			cardTitle: " KPIs, Monitoring, Closed/Open Loop Service Assurance",
			cardIcon: "Activity",
			placeholder: "Please list the main KPIs used to monitor system health",
			rows: 4,
			description:
				"Examples: CPU usage, memory utilization, response time, etc.",
			icon: "BarChart2",
		},
		{
			id: "kpiRanges",
			text: "What is the current procedure for monitoring these KPIs and their data sources? Please outline the procedure of logging into the monitoring system(s) as you would normally do it.",
			required: false,
			type: "textarea",
			cardTitle: " KPIs, Monitoring, Closed/Open Loop Service Assurance",
			placeholder:
				"Please specify ranges and time periods (e.g., CPU < 80% over 5 min avg)",
			rows: 4,
			description: "Include thresholds and sampling frequencies for each KPI",
			icon: "Activity",
		},
		{
			id: "monitoringProcedure",
			text: "Are there any currently closed loop/open loop implementations that are operational today ? Please provide the details.",
			required: false,
			type: "textarea",
			cardTitle: " KPIs, Monitoring, Closed/Open Loop Service Assurance",
			placeholder:
				"Please share the details of each of the closed or open loop including the trigger criteria with KPI or alarm based rules, information the loop provides, and any specific action(s) the loop performs.",
			rows: 4,
			description:
				"Specify tools, dashboards, or monitoring systems currently in use",
			icon: "Database",
		},
		{
			id: "challenges",
			text: "Are there any challenges in performing health checks?",
			required: false,
			type: "textarea",
			cardTitle: "Challenges and Improvements",
			cardIcon: "HelpCircle",
			placeholder:
				"Please describe any challenges or obstacles you face when performing health checks",
			rows: 4,
			maxLength: 500,
			description:
				"Include any technical issues, resource constraints, or process bottlenecks",
			highlight: "Important",
		},
		{
			id: "improvements",
			text: "What suggestions or ideas do you have to improve the way health checks is being done for your NF?",
			required: false,
			type: "textarea",
			cardTitle: "Challenges and Improvements",
			placeholder: "Please share your ideas for improvement",
			rows: 4,
			maxLength: 500,
			description:
				"Consider automation, process efficiency, and better monitoring solutions",
		},
	],
	...commonSubmitValidation,
};

// Updated Pre-Install Schema
export const preInstallSchema = {
	sectionName: "preinstall",
	sectionTitle: "Deployment - Pre-Install Steps",
	sectionIcon: "FileCheck",
	sectionColor: "emerald",
	sectionDescription: "Tasks performed before installing the NF software",
	questions: [
		{
			id: "hasMOPs",
			text: "Does your NF have MOPs available for performing Pre-Install steps? If so, please upload the MOPs in the next question. These can be vendor-provided and/or Verizon-created MOPs.",
			required: true,
			type: "radio",
			cardTitle: "MOP Availability",
			cardIcon: "FileCheck",
			options: [
				{ value: "yes", label: "Yes" },
				{ value: "no", label: "No" },
			],
			conditionalQuestions: {
				yes: ["uploadMOPs"],
			},
		},
		{
			id: "uploadMOPs",
			text: "Please upload the MOPs for Pre-Install steps. MOPs must be uploaded together; incremental updates are supported.",
			required: true,
			type: "file",
			maxFiles: 10,
			maxSingleFileSizeInMB: 30,
			maxUploadSizeInMB: 300,
			acceptedFormats: ["pdf", "docx", "xlsx"],
			hidden: true,
		},
		{
			id: "stepsCount",
			text: "How many steps are involved in the Pre-Install steps?",
			required: true,
			type: "number",
			cardTitle: "Process Details",
			cardIcon: "Clock",
			placeholder: "Enter number of steps",
			description:
				"Enter the total number of discrete steps in the pre-isntall process",
			icon: "Activity",
			unit: "steps",
		},
		{
			id: "hasAutomation",
			text: "Has any automation been developed for performing Pre-Install steps?",
			required: true,
			type: "radio",
			cardTitle: "Automation Status",
			cardIcon: "Terminal",
			options: [
				{
					value: "yes",
					label: "Yes",
					description: "Fully automated",
					color: "green",
				},
				{
					value: "partial",
					label: "Partial",
					description: "Some steps automated",
					color: "blue",
				},
				{
					value: "no",
					label: "No",
					description: "Completely manual",
					color: "red",
				},
			],
			conditionalQuestions: {
				yes: [
					"automationLinks",
					"uploadAutomationDocs",
					"automatedStepsCount",
					"minutesCount",
					"automationPayload",
					"validationMechanisms",
				],
				partial: [
					"automationLinks",
					"uploadAutomationDocs",
					"automatedStepsCount",
					"validationMechanisms",
				],
			},
		},
		{
			id: "automationLinks",
			text: "Please provide the links to the automations in comma seperated format",
			required: true,
			type: "textarea",
			placeholder: "e.g GIT or ATLAS or Google Drive",
			rows: 2,
			hidden: true,
		},
		{
			id: "uploadAutomationDocs",
			text: "If you have a seperate MOP for automation please upload here. MOPs must be uploaded together; incremental updates are not supported",
			required: false,
			type: "file",
			maxFiles: 10,
			maxSingleFileSizeInMB: 30,
			maxUploadSizeInMB: 300,
			acceptedFormats: ["pdf", "docx", "xlsx"],
			hidden: true,
		},
		{
			id: "automatedStepsCount",
			text: "Please provide the total number of steps that are automated.",
			required: true,
			type: "number",
			placeholder: "# of Steps",
			rows: 2,
			hidden: true,
			icon: "Activity",
			unit: "steps",
		},
		{
			id: "minutesCount",
			text: "How many minutes does it take to complete the automated process?",
			required: false,
			type: "number",
			placeholder: "Enter number of minutes",
			description: "Average time to complete pre-installation tasks manually",
			icon: "Clock",
			unit: "minutes",
			hidden: true,
		},
		{
			id: "automationPayload",
			text: "Is there automation to generate payloads required for above automations?",
			required: false,
			type: "radio",
			options: [
				{ value: "yes", label: "Yes" },
				{ value: "no", label: "No" },
			],
			hidden: true,
		},
		{
			id: "validationMechanisms",
			text: "What mechanisms do you use to determine whether the Pre-Install steps (Manual or Automated) were successful or failed?",
			required: true,
			type: "checkbox",
			options: [
				{ value: "health-checks", label: "Automated Health Checks" },
				{ value: "service-status", label: "Service Status Checks" },
				{ value: "database", label: "Database Validation" },
				{ value: "e2e", label: "E2E Testing" },
				{ value: "dashboards", label: "Monitoring Dashboards" },
				{ value: "logs", label: "Log Analysis" },
				{ value: "other", label: "Other" },
			],
			conditionalQuestions: {
				other: ["otherMechanism"],
			},
			hidden: true,
		},
		{
			id: "otherMechanism",
			text: "Please specify other mechanisms",
			required: true,
			type: "text",
			placeholder: "Please specify other mechanisms",
			hidden: true,
		},
		{
			id: "challenges",
			text: "Are there any challenges in performing Pre-Install steps?",
			required: false,
			type: "textarea",
			cardTitle: "Challenges and Improvements",
			cardIcon: "HelpCircle",
			placeholder:
				"Please describe any challenges or obstacles you face when performing Pre-Install steps",
			rows: 4,
			maxLength: 500,
			description:
				"Include any technical issues, resource constraints, or process bottlenecks",
			highlight: "Important",
		},
		{
			id: "improvements",
			text: "What suggestions or ideas do you have to improve the way Pre-Install steps is being done for your NF?",
			required: false,
			type: "textarea",
			cardTitle: "Challenges and Improvements",
			placeholder: "Please share your ideas for improvement",
			rows: 4,
			maxLength: 500,
			description:
				"Consider automation, process efficiency, and better monitoring solutions",
		},
	],
	...commonSubmitValidation,
};

// Updated Install Schema
export const installSchema = {
	sectionName: "install",
	sectionTitle: "Deployment - Install Steps",
	sectionIcon: "HardDrive",
	sectionColor: "emerald",
	sectionDescription: "Tasks performed to install NF software",
	questions: [
		{
			id: "hasMOPs",
			text: "Does your NF have MOPs available for performing deployments? If so, please upload the MOPs in the next question. These can be vendor-provided and/or Verizon-created MOPs.",
			required: true,
			type: "radio",
			cardTitle: "MOP Availability",
			cardIcon: "FileCheck",
			options: [
				{ value: "yes", label: "Yes" },
				{ value: "no", label: "No" },
			],
			conditionalQuestions: {
				yes: ["uploadMOPs"],
			},
		},
		{
			id: "uploadMOPs",
			text: "If you have a separate MOP for automation, please upload it here.",
			required: true,
			type: "file",
			maxFiles: 10,
			maxSingleFileSizeInMB: 30,
			maxUploadSizeInMB: 300,
			acceptedFormats: ["pdf", "docx", "xlsx"],
			hidden: true,
		},
		{
			id: "installSteps",
			text: "How many steps are involved in the deployments?",
			required: true,
			type: "number",
			cardTitle: "Process Details",
			cardIcon: "Clock",
			placeholder: "Enter the number of steps",
			icon: "Activity",
			unit: "steps",
			description: "Enter the total number of discrete installation steps",
		},
		{
			id: "uploadStepsDoc",
			text: "What are the steps involved in the deployments? Please document and upload here. MOPs must be uploaded together; incremental updates are not supported",
			required: false,
			type: "file",
			maxFiles: 10,
			maxSingleFileSizeInMB: 30,
			maxUploadSizeInMB: 300,
			acceptedFormats: ["pdf", "docx", "xlsx"],
		},
		{
			id: "hasAutomation",
			text: "Has any automation been developed for performing deployments?",
			required: true,
			type: "radio",
			cardTitle: "Automation Status",
			cardIcon: "Terminal",
			options: [
				{
					value: "yes",
					label: "Yes",
					description: "Fully automated",
					color: "green",
				},
				{
					value: "partial",
					label: "Partial",
					description: "Some steps automated",
					color: "blue",
				},
				{
					value: "no",
					label: "No",
					description: "Completely manual",
					color: "red",
				},
			],
			conditionalQuestions: {
				yes: [
					"uploadAutomationDocs",
					"automatedStepsCount",
					"automationTime",
					"automationPayload",
				],
				partial: ["automatedStepsCount", "uploadAutomationDocs"],
			},
		},
		{
			id: "uploadAutomationDocs",
			text: "If you have a seperate MOP for automation please upload here. MOPs must be uploaded together; incremental updates are not supported",
			required: false,
			type: "file",
			maxFiles: 10,
			maxSingleFileSizeInMB: 30,
			maxUploadSizeInMB: 300,
			acceptedFormats: ["pdf", "docx", "xlsx"],
			hidden: true,
		},
		{
			id: "automatedStepsCount",
			text: "Please provide the total number of steps that are automated.",
			required: true,
			type: "number",
			icon: "Activity",
			unit: "steps",
			placeholder: "# of Steps",
			rows: 2,
			hidden: true,
		},
		{
			id: "automationTime",
			text: "How many minutes does it take to complete the automated process?",
			required: false,
			type: "number",
			placeholder: "Enter number of minutes",
			description:
				"Average time to complete the automated installation process",
			icon: "Clock",
			unit: "minutes",
			hidden: true,
		},
		{
			id: "automationPayload",
			text: "Is there automation to generate payloads required for above automations?",
			required: false,
			type: "radio",
			options: [
				{ value: "yes", label: "Yes" },
				{ value: "no", label: "No" },
			],
			hidden: true,
		},
		{
			id: "challenges",
			text: "Are there any challenges in performing Deployment steps?",
			required: false,
			type: "textarea",
			cardTitle: "Challenges and Improvements",
			cardIcon: "HelpCircle",
			placeholder:
				"Please describe any challenges or obstacles you face when performing deployment steps",
			rows: 4,
			maxLength: 500,
			description:
				"Include any technical issues, resource constraints, or process bottlenecks",
			highlight: "Important",
		},
		{
			id: "improvements",
			text: "What suggestions or ideas do you have to improve the way Deployment steps is being done for your NF?",
			required: false,
			type: "textarea",
			cardTitle: "Challenges and Improvements",
			placeholder: "Please share your ideas for improvement",
			rows: 4,
			maxLength: 500,
			description:
				"Consider automation, process efficiency, and better monitoring solutions",
		},
		{
			id: "installTime",
			text: "How many minutes does it take to complete the installation?",
			required: false,
			type: "number",
			placeholder: "Enter time",
			description: "Average time to complete the installation process",
			icon: "Clock",
			unit: "minutes",
		},
	],
	...commonSubmitValidation,
};

// Post-Install Schema
export const postInstallSchema = {
	sectionName: "postinstall",
	sectionTitle: "Deployment - Post-Install Steps",
	sectionIcon: "CheckCircle2",
	sectionColor: "emerald",
	sectionDescription: "Tasks performed to configure the NF (Day-x)",
	questions: [
		{
			id: "hasMOPs",
			text: "Does your NF have MOPs available for performing Post-Install? If so, please upload the MOPs in the next question. These can be vendor-provided and/or Verizon-created MOPs.",
			required: true,
			type: "radio",
			cardTitle: "MOP Availability",
			cardIcon: "FileCheck",
			options: [
				{ value: "yes", label: "Yes" },
				{ value: "no", label: "No" },
			],
			conditionalQuestions: {
				yes: ["uploadMOPs"],
			},
		},
		{
			id: "uploadMOPs",
			text: "Please upload the MOPs for Post-Install. MOPs must be uploaded together; incremental updates are supported.",
			required: true,
			type: "file",
			maxFiles: 10,
			maxSingleFileSizeInMB: 30,
			maxUploadSizeInMB: 300,
			acceptedFormats: ["pdf", "docx", "xlsx"],
			hidden: true,
		},
		{
			id: "postInstallSteps",
			text: "How many steps are involved in the Post-Install?",
			required: true,
			type: "number",
			cardTitle: "Process Details",
			cardIcon: "Clock",
			placeholder: "Enter the number of steps",
			icon: "Activity",
			unit: "steps",
			description: "Enter the total number of discrete post-installation steps",
		},
		{
			id: "uploadStepsDoc",
			text: "What are the steps involved in the Post-Install? Please document and upload here. MOPs must be uploaded together; incremental updates are not supported",
			required: false,
			type: "file",
			maxFiles: 10,
			maxSingleFileSizeInMB: 30,
			maxUploadSizeInMB: 300,
			acceptedFormats: ["pdf", "docx", "xlsx"],
		},
		{
			id: "hasAutomation",
			text: "Has any automation been developed for performing Post deployments?",
			required: true,
			type: "radio",
			cardTitle: "Automation Status",
			cardIcon: "Terminal",
			options: [
				{
					value: "yes",
					label: "Yes",
					description: "Fully automated",
					color: "green",
				},
				{
					value: "partial",
					label: "Partial",
					description: "Some steps automated",
					color: "blue",
				},
				{
					value: "no",
					label: "No",
					description: "Completely manual",
					color: "red",
				},
			],
			conditionalQuestions: {
				yes: [
					"uploadAutomationDocs",
					"automatedStepsCount",
					"automationTime",
					"automationPayload",
					"validationMechanisms",
				],
				partial: [
					"uploadAutomationDocs",
					"automatedStepsCount",
					"validationMechanisms",
				],
			},
		},
		{
			id: "uploadAutomationDocs",
			text: "If you have a seperate MOP for automation please upload here. MOPs must be uploaded together; incremental updates are not supported",
			required: false,
			type: "file",
			maxFiles: 10,
			maxSingleFileSizeInMB: 30,
			maxUploadSizeInMB: 300,
			acceptedFormats: ["pdf", "docx", "xlsx"],
			hidden: true,
		},
		{
			id: "automatedStepsCount",
			text: "Please provide the total number of steps that are automated.",
			required: true,
			type: "number",
			icon: "Activity",
			unit: "steps",
			placeholder: "# of Steps",
			rows: 2,
			hidden: true,
		},
		{
			id: "automationTime",
			text: "How many minutes does it take to complete the automated process?",
			required: false,
			type: "number",
			placeholder: "Enter number of minutes",
			description:
				"Average time to complete the automated post-installation process",
			icon: "Clock",
			unit: "minutes",
			hidden: true,
		},
		{
			id: "automationPayload",
			text: "Is there automation to generate payloads required for above automations?",
			required: false,
			type: "radio",
			options: [
				{ value: "yes", label: "Yes" },
				{ value: "no", label: "No" },
			],
			hidden: true,
		},
		{
			id: "validationMechanisms",
			text: "What mechanisms do you use to determine whether the Post Install steps were successful or failed?",
			required: true,
			type: "checkbox",
			options: [
				{ value: "health-checks", label: "Automated Health Checks" },
				{ value: "service-status", label: "Service Status Checks" },
				{ value: "database", label: "Database Validation" },
				{ value: "e2e", label: "E2E Testing" },
				{ value: "dashboards", label: "Monitoring Dashboards" },
				{ value: "logs", label: "Log Analysis" },
				{ value: "other", label: "Other" },
			],
			conditionalQuestions: {
				other: ["otherMechanism"],
			},
			hidden: true,
		},
		{
			id: "otherMechanism",
			text: "Please specify other mechanisms",
			required: true,
			type: "text",
			placeholder: "Please specify other mechanisms",
			hidden: true,
		},
		{
			id: "challenges",
			text: "Are there any challenges in performing Post-Install steps?",
			required: false,
			type: "textarea",
			cardTitle: "Challenges and Improvements",
			cardIcon: "HelpCircle",
			placeholder:
				"Please describe any challenges or obstacles you face when performing Post-Install steps",
			rows: 4,
			maxLength: 500,
			description:
				"Include any technical issues, resource constraints, or process bottlenecks",
			highlight: "Important",
		},
		{
			id: "improvements",
			text: "What suggestions or ideas do you have to improve the way Post-Install steps is being done for your NF?",
			required: false,
			type: "textarea",
			cardTitle: "Challenges and Improvements",
			placeholder: "Please share your ideas for improvement",
			rows: 4,
			maxLength: 500,
			description:
				"Consider automation, process efficiency, and better monitoring solutions",
		},
		// {
		//   "id": "postInstallTime",
		//   "text": "How many minutes does it take to complete the post-installation?",
		//   "required": false,
		//   "type": "number",
		//   "placeholder": "Enter time",
		//   "description": "Average time to complete the post-installation process",
		//   "icon": "Clock",
		//   "unit": "minutes"
		// }
	],
	...commonSubmitValidation,
};

export const preUpgradeSchema = {
	sectionName: "preupgrade",
	sectionTitle: "Upgrade - Pre-Checks Steps",
	sectionIcon: "FileCheck",
	sectionColor: "purple",
	sectionDescription: "Tasks performed before upgrading the NF software.",
	questions: [
		{
			id: "hasMOPs",
			text: "Does your NF have MOPs available for performing Upgrade Pre-checks? If so, please upload the MOPs in the next question. These can be vendor-provided and/or Verizon-created MOPs.",
			required: true,
			type: "radio",
			cardTitle: "MOP Availability",
			cardIcon: "FileCheck",
			options: [
				{ value: "yes", label: "Yes" },
				{ value: "no", label: "No" },
			],
			conditionalQuestions: {
				yes: ["uploadMOPs"],
			},
		},
		{
			id: "uploadMOPs",
			text: "Please upload the MOPs for Upgrade Pre-checks. MOPs must be uploaded together; incremental updates are supported.",
			required: true,
			type: "file",
			maxFiles: 10,
			maxSingleFileSizeInMB: 30,
			maxUploadSizeInMB: 300,
			acceptedFormats: ["pdf", "docx", "xlsx"],
			hidden: true,
		},
		{
			id: "stepsCount",
			text: "How many steps are involved in the Upgrade Pre-checks?",
			required: true,
			type: "number",
			cardTitle: "Process Details",
			cardIcon: "Clock",
			placeholder: "Enter the number of steps",
			icon: "Activity",
			unit: "steps",
			description:
				"Enter the total number of discrete steps in the upgrade pre-check process",
		},
		{
			id: "uploadStepsDoc",
			text: "What are the steps involved in the Upgrade Pre-checks? Please document and upload here. MOPs must be uploaded together; incremental updates are not supported.",
			required: false,
			type: "file",
			maxFiles: 10,
			maxSingleFileSizeInMB: 30,
			maxUploadSizeInMB: 300,
			acceptedFormats: ["pdf", "docx", "xlsx"],
		},
		{
			id: "hasAutomation",
			text: "Has any automation been developed for performing Upgrade Pre-checks?",
			required: true,
			type: "radio",
			cardTitle: "Automation Status",
			cardIcon: "Terminal",
			options: [
				{
					value: "yes",
					label: "Yes",
					description: "Fully automated",
					color: "green",
				},
				{
					value: "partial",
					label: "Partial",
					description: "Some steps automated",
					color: "blue",
				},
				{
					value: "no",
					label: "No",
					description: "Completely manual",
					color: "red",
				},
			],
			conditionalQuestions: {
				yes: [
					"uploadAutomationDocs",
					"automatedStepsCount",
					"automationTime",
					"automationPayload",
					"validationMechanisms",
				],
				partial: [
					"uploadAutomationDocs",
					"automatedStepsCount",
					"validationMechanisms",
				],
			},
		},
		{
			id: "uploadAutomationDocs",
			text: "If you have a separate MOP for automation please upload here. MOPs must be uploaded together; incremental updates are not supported.",
			required: false,
			type: "file",
			maxFiles: 10,
			maxSingleFileSizeInMB: 30,
			maxUploadSizeInMB: 300,
			acceptedFormats: ["pdf", "docx", "xlsx"],
			hidden: true,
		},
		{
			id: "automatedStepsCount",
			text: "Please provide the total number of steps that are automated.",
			required: true,
			type: "number",
			icon: "Activity",
			unit: "steps",
			placeholder: "# of Steps",
			rows: 2,
			hidden: true,
		},
		{
			id: "automationTime",
			text: "How many minutes does it take to complete the automated process?",
			required: false,
			type: "number",
			placeholder: "Enter number of minutes",
			description: "Average time to complete the automated pre-check process",
			icon: "Clock",
			unit: "minutes",
			hidden: true,
		},
		{
			id: "automationPayload",
			text: "Is there automation to generate payloads required for above automations?",
			required: false,
			type: "radio",
			options: [
				{ value: "yes", label: "Yes" },
				{ value: "no", label: "No" },
			],
			hidden: true,
		},
		{
			id: "validationMechanisms",
			text: "What mechanisms do you use to determine whether the Upgrade Pre-Check steps were successful or failed?",
			required: true,
			type: "checkbox",
			options: [
				{ value: "health-checks", label: "Automated Health Checks" },
				{ value: "service-status", label: "Service Status Checks" },
				{ value: "database", label: "Database Validation" },
				{ value: "e2e", label: "E2E Testing" },
				{ value: "dashboards", label: "Monitoring Dashboards" },
				{ value: "logs", label: "Log Analysis" },
				{ value: "other", label: "Other" },
			],
			conditionalQuestions: {
				other: ["otherMechanism"],
			},
			hidden: true,
		},
		{
			id: "otherMechanism",
			text: "Please specify other mechanisms",
			required: true,
			type: "text",
			placeholder: "Please specify other mechanisms",
			hidden: true,
		},
		{
			id: "challenges",
			text: "Are there any challenges in performing Upgrade Pre-checks steps?",
			required: false,
			type: "textarea",
			cardTitle: "Challenges and Improvements",
			cardIcon: "HelpCircle",
			placeholder:
				"Please describe any challenges or obstacles you face when performing Upgrade Pre-checks steps",
			rows: 4,
			maxLength: 500,
			description:
				"Include any technical issues, resource constraints, or process bottlenecks",
			highlight: "Important",
		},
		{
			id: "improvements",
			text: "What suggestions or ideas do you have to improve the way Upgrade Pre-checks steps is being done for your NF?",
			required: false,
			type: "textarea",
			cardTitle: "Challenges and Improvements",
			placeholder: "Please share your ideas for improvement",
			rows: 4,
			maxLength: 500,
			description:
				"Consider automation, process efficiency, and better monitoring solutions",
		},
	],
	...commonSubmitValidation,
};

export const upgradeSchema = {
	sectionName: "upgrade",
	sectionTitle: "Upgrade - Upgrade Steps",
	sectionIcon: "Zap",
	sectionColor: "purple",
	sectionDescription: "Tasks performed to upgrade the NF software version.",
	questions: [
		{
			id: "hasMOPs",
			text: "Does your NF have MOPs available for performing Upgrades? If so, please upload the MOPs in the next question. These can be vendor-provided and/or Verizon-created MOPs.",
			required: true,
			type: "radio",
			cardTitle: "MOP Availability",
			cardIcon: "FileCheck",
			options: [
				{ value: "yes", label: "Yes" },
				{ value: "no", label: "No" },
			],
			conditionalQuestions: {
				yes: ["uploadMOPs"],
			},
		},
		{
			id: "uploadMOPs",
			text: "Please upload the MOPs for Upgrades. MOPs must be uploaded together; incremental updates are supported.",
			required: true,
			type: "file",
			maxFiles: 10,
			maxSingleFileSizeInMB: 30,
			maxUploadSizeInMB: 300,
			acceptedFormats: ["pdf", "docx", "xlsx"],
			hidden: true,
		},
		{
			id: "stepsCount",
			text: "How many steps are involved in the Upgrades?",
			required: true,
			type: "number",
			cardTitle: "Process Details",
			cardIcon: "Clock",
			placeholder: "Enter the number of steps",
			icon: "Activity",
			unit: "steps",
			description:
				"Enter the total number of discrete steps in the upgrade process",
		},
		{
			id: "uploadStepsDoc",
			text: "What are the steps involved in the Upgrades? Please document and upload here. MOPs must be uploaded together; incremental updates are not supported.",
			required: false,
			type: "file",
			maxFiles: 10,
			maxSingleFileSizeInMB: 30,
			maxUploadSizeInMB: 300,
			acceptedFormats: ["pdf", "docx", "xlsx"],
		},
		{
			id: "hasAutomation",
			text: "Has any automation been developed for performing Upgrades?",
			required: true,
			type: "radio",
			cardTitle: "Automation Status",
			cardIcon: "Terminal",
			options: [
				{
					value: "yes",
					label: "Yes",
					description: "Fully automated",
					color: "green",
				},
				{
					value: "partial",
					label: "Partial",
					description: "Some steps automated",
					color: "blue",
				},
				{
					value: "no",
					label: "No",
					description: "Completely manual",
					color: "red",
				},
			],
			conditionalQuestions: {
				yes: [
					"uploadAutomationDocs",
					"automatedStepsCount",
					"automationTime",
					"automationPayload",
					"validationMechanisms",
				],
				partial: [
					"uploadAutomationDocs",
					"automatedStepsCount",
					"validationMechanisms",
				],
			},
		},
		{
			id: "uploadAutomationDocs",
			text: "If you have a separate MOP for automation please upload here. MOPs must be uploaded together; incremental updates are not supported.",
			required: false,
			type: "file",
			maxFiles: 10,
			maxSingleFileSizeInMB: 30,
			maxUploadSizeInMB: 300,
			acceptedFormats: ["pdf", "docx", "xlsx"],
			hidden: true,
		},
		{
			id: "automatedStepsCount",
			text: "Please provide the total number of steps that are automated.",
			required: true,
			type: "number",
			icon: "Activity",
			unit: "steps",
			placeholder: "# of Steps",
			rows: 2,
			hidden: true,
		},
		{
			id: "automationTime",
			text: "How many minutes does it take to complete the automated process?",
			required: false,
			type: "number",
			placeholder: "Enter number of minutes",
			description: "Average time to complete the automated upgrade process",
			icon: "Clock",
			unit: "minutes",
			hidden: true,
		},
		{
			id: "automationPayload",
			text: "Is there automation to generate payloads required for above automations?",
			required: false,
			type: "radio",
			options: [
				{ value: "yes", label: "Yes" },
				{ value: "no", label: "No" },
			],
			hidden: true,
		},
		{
			id: "validationMechanisms",
			text: "What mechanisms do you use to determine whether the Upgrade steps were successful or failed?",
			required: true,
			type: "checkbox",
			options: [
				{ value: "health-checks", label: "Automated Health Checks" },
				{ value: "service-status", label: "Service Status Checks" },
				{ value: "database", label: "Database Validation" },
				{ value: "e2e", label: "E2E Testing" },
				{ value: "dashboards", label: "Monitoring Dashboards" },
				{ value: "logs", label: "Log Analysis" },
				{ value: "other", label: "Other" },
			],
			conditionalQuestions: {
				other: ["otherMechanism"],
			},
			hidden: true,
		},
		{
			id: "otherMechanism",
			text: "Please specify other mechanisms",
			required: true,
			type: "text",
			placeholder: "Please specify other mechanisms",
			hidden: true,
		},
		{
			id: "challenges",
			text: "Are there any challenges in performing Upgrade steps?",
			required: false,
			type: "textarea",
			cardTitle: "Challenges and Improvements",
			cardIcon: "HelpCircle",
			placeholder:
				"Please describe any challenges or obstacles you face when performing Upgrade steps",
			rows: 4,
			maxLength: 500,
			description:
				"Include any technical issues, resource constraints, or process bottlenecks",
			highlight: "Important",
		},
		{
			id: "improvements",
			text: "What suggestions or ideas do you have to improve the way Upgrade steps is being done for your NF?",
			required: false,
			type: "textarea",
			cardTitle: "Challenges and Improvements",
			placeholder: "Please share your ideas for improvement",
			rows: 4,
			maxLength: 500,
			description:
				"Consider automation, process efficiency, and better monitoring solutions",
		},
	],
	...commonSubmitValidation,
};

// Post-Upgrade Schema
export const postUpgradeSchema = {
	sectionName: "postupgrade",
	sectionTitle: "Upgrade - Post-Checks Steps",
	sectionIcon: "CheckCircle2",
	sectionColor: "purple",
	sectionDescription: "Tasks performed after upgrading the NF software version",
	questions: [
		{
			id: "hasMOPs",
			text: "Does your NF have MOPs available for performing Upgrade Post-checks? If so, please upload the MOPs in the next question. These can be vendor-provided and/or Verizon-created MOPs.",
			required: true,
			type: "radio",
			cardTitle: "MOP Availability",
			cardIcon: "FileCheck",
			options: [
				{ value: "yes", label: "Yes" },
				{ value: "no", label: "No" },
			],
			conditionalQuestions: {
				yes: ["uploadMOPs"],
			},
		},
		{
			id: "uploadMOPs",
			text: "Please upload the MOPs for Upgrade Post-checks. MOPs must be uploaded together; incremental updates are supported.",
			required: true,
			type: "file",
			maxFiles: 10,
			maxSingleFileSizeInMB: 30,
			maxUploadSizeInMB: 300,
			acceptedFormats: ["pdf", "docx", "xlsx"],
			hidden: true,
		},
		{
			id: "stepsCount",
			text: "How many steps are involved in the Upgrade Post-checks?",
			required: true,
			type: "number",
			cardTitle: "Process Details",
			cardIcon: "Clock",
			placeholder: "Enter the number of steps",
			icon: "Activity",
			unit: "steps",
			description:
				"Enter the total number of discrete steps in the upgrade post-check process",
		},
		{
			id: "uploadStepsDoc",
			text: "What are the steps involved in the Upgrade Post-checks? Please document and upload here. MOPs must be uploaded together; incremental updates are not supported.",
			required: false,
			type: "file",
			maxFiles: 10,
			maxSingleFileSizeInMB: 30,
			maxUploadSizeInMB: 300,
			acceptedFormats: ["pdf", "docx", "xlsx"],
		},
		{
			id: "hasAutomation",
			text: "Has any automation been developed for performing Upgrade Post-checks?",
			required: true,
			type: "radio",
			cardTitle: "Automation Status",
			cardIcon: "Terminal",
			options: [
				{
					value: "yes",
					label: "Yes",
					description: "Fully automated",
					color: "green",
				},
				{
					value: "partial",
					label: "Partial",
					description: "Some steps automated",
					color: "blue",
				},
				{
					value: "no",
					label: "No",
					description: "Completely manual",
					color: "red",
				},
			],
			conditionalQuestions: {
				yes: [
					"uploadAutomationDocs",
					"automatedStepsCount",
					"automationTime",
					"automationPayload",
					"validationMechanisms",
				],
				partial: [
					"uploadAutomationDocs",
					"automatedStepsCount",
					"validationMechanisms",
				],
			},
		},
		{
			id: "uploadAutomationDocs",
			text: "If you have a separate MOP for automation please upload here. MOPs must be uploaded together; incremental updates are not supported.",
			required: false,
			type: "file",
			maxFiles: 10,
			maxSingleFileSizeInMB: 30,
			maxUploadSizeInMB: 300,
			acceptedFormats: ["pdf", "docx", "xlsx"],
			hidden: true,
		},
		{
			id: "automatedStepsCount",
			text: "Please provide the total number of steps that are automated.",
			required: true,
			type: "number",
			icon: "Activity",
			unit: "steps",
			placeholder: "# of Steps",
			rows: 2,
			hidden: true,
		},
		{
			id: "automationTime",
			text: "How many minutes does it take to complete the automated process?",
			required: false,
			type: "number",
			placeholder: "Enter number of minutes",
			description: "Average time to complete the automated post-check process",
			icon: "Clock",
			unit: "minutes",
			hidden: true,
		},
		{
			id: "automationPayload",
			text: "Is there automation to generate payloads required for above automations?",
			required: false,
			type: "radio",
			options: [
				{ value: "yes", label: "Yes" },
				{ value: "no", label: "No" },
			],
			hidden: true,
		},
		{
			id: "validationMechanisms",
			text: "What mechanisms do you use to determine whether the Upgrade Post-Check steps were successful or failed?",
			required: true,
			type: "checkbox",
			options: [
				{ value: "health-checks", label: "Automated Health Checks" },
				{ value: "service-status", label: "Service Status Checks" },
				{ value: "database", label: "Database Validation" },
				{ value: "e2e", label: "E2E Testing" },
				{ value: "dashboards", label: "Monitoring Dashboards" },
				{ value: "logs", label: "Log Analysis" },
				{ value: "other", label: "Other" },
			],
			conditionalQuestions: {
				other: ["otherMechanism"],
			},
			hidden: true,
		},
		{
			id: "otherMechanism",
			text: "Please specify other mechanisms",
			required: true,
			type: "text",
			placeholder: "Please specify other mechanisms",
			hidden: true,
		},
		{
			id: "challenges",
			text: "Are there any challenges in performing Upgrade Post-checks steps?",
			required: false,
			type: "textarea",
			cardTitle: "Challenges and Improvements",
			cardIcon: "HelpCircle",
			placeholder:
				"Please describe any challenges or obstacles you face when performing Upgrade Post-checks steps",
			rows: 4,
			maxLength: 500,
			description:
				"Include any technical issues, resource constraints, or process bottlenecks",
			highlight: "Important",
		},
		{
			id: "improvements",
			text: "What suggestions or ideas do you have to improve the way Upgrade Post-checks steps is being done for your NF?",
			required: false,
			type: "textarea",
			cardTitle: "Challenges and Improvements",
			placeholder: "Please share your ideas for improvement",
			rows: 4,
			maxLength: 500,
			description:
				"Consider automation, process efficiency, and better monitoring solutions",
		},
	],
	...commonSubmitValidation,
};

// Config Audit Schema
export const configAuditSchema = {
	sectionName: "configaudit",
	sectionTitle: "Config Audit",
	sectionIcon: "FileText",
	sectionColor: "amber",
	sectionDescription:
		"Tasks performed to ensure the NF configuration aligns with the baseline or golden configuration",
	questions: [
		{
			id: "hasMOPs",
			text: "Does your NF have MOPs available for performing Config Audits? If so, please upload the MOPs in the next question. These can be vendor-provided and/or Verizon-created MOPs.",
			required: true,
			type: "radio",
			cardTitle: "MOP Availability",
			cardIcon: "FileCheck",
			options: [
				{ value: "yes", label: "Yes" },
				{ value: "no", label: "No" },
			],
			conditionalQuestions: {
				yes: ["uploadMOPs"],
			},
		},
		{
			id: "undocumentedSteps",
			text: "Do you perform any configuration audit steps that are not documented in any Method of Procedure (MOP)? If yes, please provide a list of those steps, including: Actions performed Features List How they are executed (e.g., GUI , CLI , API , scripts, and tools etc..) Expected results Remediation procedures in case of failure \n\nExample answer: https://docs.google.com/document/d/1dYvzp0X8pM7pHBeMgjb-VI_d0Q3TB9ahfwNNIhutc-4/edit?tab=t.0",
			required: false,
			cardTitle: "MOP Availability",
			cardIcon: "Terminal",
			type: "textarea",
			placeholder: "Your steps here:",
			rows: 4,
		},
		{
			id: "supportingDocs",
			text: "You may also upload supporting documentation if available.",
			cardTitle: "MOP Availability",
			required: false,
			type: "file",
			maxFiles: 10,
			maxSingleFileSizeInMB: 30,
			maxUploadSizeInMB: 300,
			acceptedFormats: ["pdf", "docx", "xlsx"],
			hidden: false,
		},
		{
			id: "hasGoldenConfig",
			text: "Do you have a golden configuration for all the audited features?",
			required: true,
			type: "radio",
			cardTitle: "MOP Availability",
			cardIcon: "FileCheck",
			options: [
				{ value: "yes", label: "Yes" },
				{ value: "no", label: "No" },
			],
			conditionalQuestions: {
				yes: ["uploadConfig"],
			},
		},
		{
			id: "uploadConfig",
			text: "Upload the corresponding golden configuration files.",
			required: true,
			type: "file",
			cardTitle: "MOP Availability",
			maxFiles: 10,
			maxSingleFileSizeInMB: 30,
			maxUploadSizeInMB: 300,
			acceptedFormats: ["pdf", "docx", "xlsx"],
			hidden: true,
		},
		{
			id: "uploadMOPs",
			text: "Please upload the MOPs for Config Audits. MOPs must be uploaded together; incremental updates are not supported.",
			required: true,
			type: "file",
			maxFiles: 10,
			maxSingleFileSizeInMB: 30,
			maxUploadSizeInMB: 300,
			acceptedFormats: ["pdf", "docx", "xlsx"],
			hidden: true,
		},
		{
			id: "stepsCount",
			text: "How many steps are involved in the Config Audits?",
			required: true,
			type: "number",
			cardTitle: "Process Details",
			cardIcon: "Clock",
			placeholder: "Enter the number of steps",
			icon: "Activity",
			unit: "steps",
			description:
				"Enter the total number of discrete steps in the config audit process",
		},
		{
			id: "frequencyAudit",
			text: "What should be the frequency for configuration audits?",
			required: true,
			cardTitle: "Process Details",
			cardIcon: "Terminal",
			type: "textarea",
			placeholder: "Please specify the exact day and time. \nExample: Once a week on Sunday at 3:00 AM ET.",
			rows: 4,
		},
		{
			id: "uploadStepsDoc",
			text: "What are the steps involved in the Config Audits? Please document and upload here. MOPs must be uploaded together; incremental updates are not supported.",
			required: false,
			type: "file",
			maxFiles: 10,
			maxSingleFileSizeInMB: 30,
			maxUploadSizeInMB: 300,
			acceptedFormats: ["pdf", "docx", "xlsx"],
		},
		{
			id: "hasAutomation",
			text: "Has any automation been developed for performing the Config Audits?",
			required: true,
			type: "radio",
			cardTitle: "Automation Status",
			cardIcon: "Terminal",
			options: [
				{
					value: "yes",
					label: "Yes",
					description: "Fully automated",
					color: "green",
				},
				{
					value: "partial",
					label: "Partial",
					description: "Some steps automated",
					color: "blue",
				},
				{
					value: "no",
					label: "No",
					description: "Completely manual",
					color: "red",
				},
			],
			conditionalQuestions: {
				yes: [
					"uploadAutomationDocs",
					"automatedStepsCount",
					"automationTime",
					"automationPayload",
					"validationMechanisms",
				],
				partial: [
					"uploadAutomationDocs",
					"automatedStepsCount",
					"validationMechanisms",
				],
			},
		},
		{
			id: "uploadAutomationDocs",
			text: "If you have a separate MOP for automation please upload here. MOPs must be uploaded together; incremental updates are not supported.",
			required: false,
			type: "file",
			maxFiles: 10,
			maxSingleFileSizeInMB: 30,
			maxUploadSizeInMB: 300,
			acceptedFormats: ["pdf", "docx", "xlsx"],
			hidden: true,
		},
		{
			id: "automatedStepsCount",
			text: "Please provide the total number of steps that are automated.",
			required: true,
			type: "number",
			icon: "Activity",
			unit: "steps",
			placeholder: "# of Steps",
			rows: 2,
			hidden: true,
		},
		{
			id: "automationTime",
			text: "How many minutes does it take to complete the automated process?",
			required: false,
			type: "number",
			placeholder: "Enter number of minutes",
			description:
				"Average time to complete the automated config audit process",
			icon: "Clock",
			unit: "minutes",
			hidden: true,
		},
		{
			id: "automationPayload",
			text: "Is there automation to generate payloads required for above automations?",
			required: false,
			type: "radio",
			options: [
				{ value: "yes", label: "Yes" },
				{ value: "no", label: "No" },
			],
			hidden: true,
		},
		{
			id: "validationMechanisms",
			text: "What mechanisms do you use to determine whether the Config Audit steps were successful or failed?",
			required: true,
			type: "checkbox",
			options: [
				{ value: "health-checks", label: "Automated Health Checks" },
				{ value: "service-status", label: "Service Status Checks" },
				{ value: "database", label: "Database Validation" },
				{ value: "e2e", label: "E2E Testing" },
				{ value: "dashboards", label: "Monitoring Dashboards" },
				{ value: "logs", label: "Log Analysis" },
				{ value: "other", label: "Other" },
			],
			conditionalQuestions: {
				other: ["otherMechanism"],
			},
			hidden: true,
		},
		{
			id: "otherMechanism",
			text: "Please specify other mechanisms",
			required: true,
			type: "text",
			placeholder: "Please specify other mechanisms",
			hidden: true,
		},
		{
			id: "challenges",
			text: "Are there any challenges in performing the Config Audits?",
			required: false,
			type: "textarea",
			cardTitle: "Challenges and Improvements",
			cardIcon: "HelpCircle",
			placeholder:
				"Please describe any challenges or obstacles you face when performing Config Audits",
			rows: 4,
			maxLength: 500,
			description:
				"Include any technical issues, resource constraints, or process bottlenecks",
			highlight: "Important",
		},
		{
			id: "improvements",
			text: "What suggestions or ideas do you have to improve the way the Config Audits steps is being done for your NF?",
			required: false,
			type: "textarea",
			cardTitle: "Challenges and Improvements",
			placeholder: "Please share your ideas for improvement",
			rows: 4,
			maxLength: 500,
			description:
				"Consider automation, process efficiency, and better monitoring solutions",
		},
	],
	...commonSubmitValidation,
};

// Config Change Schema
export const configChangeSchema = {
	sectionName: "configchange",
	sectionTitle: "Config Change",
	sectionIcon: "Settings",
	sectionColor: "amber",
	sectionDescription: "Procedures for modifying NF parameter values",
	questions: [
		{
			id: "hasMOPs",
			text: "Does your NF have MOPs available for performing Config Changes? If so, please upload the MOPs in the next question. These can be vendor-provided and/or Verizon-created MOPs.",
			required: true,
			type: "radio",
			cardTitle: "MOP Availability",
			cardIcon: "FileCheck",
			options: [
				{ value: "yes", label: "Yes" },
				{ value: "no", label: "No" },
			],
			conditionalQuestions: {
				yes: ["uploadMOPs"],
			},
		},
		{
			id: "uploadMOPs",
			text: "Please upload the MOPs for Config Changes. MOPs must be uploaded together; incremental updates are not supported.",
			required: true,
			type: "file",
			maxFiles: 10,
			maxSingleFileSizeInMB: 30,
			maxUploadSizeInMB: 300,
			acceptedFormats: ["pdf", "docx", "xlsx"],
			hidden: true,
		},
		{
			id: "stepsCount",
			text: "How many steps are involved in the Config Changes?",
			required: true,
			type: "number",
			cardTitle: "Process Details",
			cardIcon: "Clock",
			placeholder: "Enter the number of steps",
			icon: "Activity",
			unit: "steps",
			description:
				"Enter the total number of discrete steps in the config change process",
		},
		{
			id: "uploadStepsDoc",
			text: "What are the steps involved in the Config Changes? Please document and upload here. MOPs must be uploaded together; incremental updates are not supported.",
			required: false,
			type: "file",
			maxFiles: 10,
			maxSingleFileSizeInMB: 30,
			maxUploadSizeInMB: 300,
			acceptedFormats: ["pdf", "docx", "xlsx"],
		},
		{
			id: "hasAutomation",
			text: "Has any automation been developed for performing Config Changes?",
			required: true,
			type: "radio",
			cardTitle: "Automation Status",
			cardIcon: "Terminal",
			options: [
				{
					value: "yes",
					label: "Yes",
					description: "Fully automated",
					color: "green",
				},
				{
					value: "partial",
					label: "Partial",
					description: "Some steps automated",
					color: "blue",
				},
				{
					value: "no",
					label: "No",
					description: "Completely manual",
					color: "red",
				},
			],
			conditionalQuestions: {
				yes: [
					"automatedStepsCount",
					"uploadAutomationDocs",
					"minutesCount",
					"automationPayload",
					"validationMechanisms",
				],
				partial: [
					"automatedStepsCount",
					"uploadAutomationDocs",
					"validationMechanisms",
				],
			},
		},
		{
			id: "automatedStepsCount",
			text: "Please provide the total number of steps that are automated.",
			required: true,
			type: "number",
			icon: "Activity",
			unit: "steps",
			placeholder: "# of Steps",
			rows: 2,
			hidden: true,
		},
		{
			id: "uploadAutomationDocs",
			text: "If you have a separate MOP for automation please upload here. MOPs must be uploaded together; incremental updates are not supported.",
			required: false,
			type: "file",
			maxFiles: 10,
			maxSingleFileSizeInMB: 30,
			maxUploadSizeInMB: 300,
			acceptedFormats: ["pdf", "docx", "xlsx"],
			hidden: true,
		},
		{
			id: "minutesCount",
			text: "How many minutes does it take to complete the automated process?",
			required: false,
			type: "number",
			placeholder: "Enter time",
			description: "Average time to complete all Upgrade steps manually",
			icon: "Clock",
			unit: "minutes",
			hidden: true,
		},
		{
			id: "automationPayload",
			text: "Is there automation to generate payloads required for above automations?",
			required: false,
			type: "radio",
			options: [
				{ value: "yes", label: "Yes" },
				{ value: "no", label: "No" },
			],
			hidden: true,
		},
		{
			id: "validationMechanisms",
			text: "What mechanisms do you use to determine whether the Config Changes steps were successful or failed?",
			required: true,
			type: "checkbox",
			options: [
				{ value: "health-checks", label: "Automated Health Checks" },
				{ value: "service-status", label: "Service Status Checks" },
				{ value: "database", label: "Database Validation" },
				{ value: "e2e", label: "E2E Testing" },
				{ value: "dashboards", label: "Monitoring Dashboards" },
				{ value: "logs", label: "Log Analysis" },
				{ value: "other", label: "Other" },
			],
			conditionalQuestions: {
				other: ["otherMechanism"],
			},
			hidden: true,
		},
		{
			id: "otherMechanism",
			text: "Please specify other mechanisms",
			required: true,
			type: "text",
			placeholder: "Please specify other mechanisms",
			hidden: true,
		},
		{
			id: "challenges",
			text: "Are there any challenges in performing Config Changes?",
			required: false,
			type: "textarea",
			cardTitle: "Challenges and Improvements",
			cardIcon: "HelpCircle",
			placeholder:
				"Please describe any challenges or obstacles you face when performing Config Changes",
			rows: 4,
			maxLength: 500,
			description:
				"Include any technical issues, resource constraints, or process bottlenecks",
			highlight: "Important",
		},
		{
			id: "improvements",
			text: "What suggestions or ideas do you have to improve the way Config Changes steps is being done for your NF?",
			required: false,
			type: "textarea",
			cardTitle: "Challenges and Improvements",
			placeholder: "Please share your ideas for improvement",
			rows: 4,
			maxLength: 500,
			description:
				"Consider automation, process efficiency, and better monitoring solutions",
		},
	],
	...commonSubmitValidation,
};

// Rollback Schema
export const rollbackSchema = {
	sectionName: "rollback",
	sectionTitle: "Rollback Automations",
	sectionIcon: "RefreshCw",
	sectionColor: "red",
	sectionDescription:
		"Tasks performed to revert the NF to a previous software or configuration version",
	questions: [
		{
			id: "hasMOPs",
			text: "Does your NF have MOPs available for performing Rollback Automations?",
			required: true,
			type: "radio",
			cardTitle: "MOP Availability",
			cardIcon: "FileCheck",
			options: [
				{ value: "yes", label: "Yes" },
				{ value: "no", label: "No" },
			],
			conditionalQuestions: {
				yes: ["uploadMOPs"],
			},
		},
		{
			id: "uploadMOPs",
			text: "Please upload the MOPs for Rollback Automations. MOPs must be uploaded together; incremental updates are not supported.",
			required: true,
			type: "file",
			maxFiles: 10,
			maxSingleFileSizeInMB: 30,
			maxUploadSizeInMB: 300,
			acceptedFormats: ["pdf", "docx", "xlsx"],
			hidden: true,
		},
		{
			id: "stepsCount",
			text: "How many steps are involved in the Rollback Automations?",
			required: true,
			type: "number",
			cardTitle: "Process Details",
			cardIcon: "Clock",
			placeholder: "Enter the number of steps",
			icon: "Activity",
			unit: "steps",
			description:
				"Enter the total number of discrete steps in the rollback process",
		},
		{
			id: "uploadStepsDoc",
			text: "What are the steps involved in the Rollback Automations? Please document and upload here. MOPs must be uploaded together; incremental updates are not supported.",
			required: false,
			type: "file",
			maxFiles: 10,
			maxSingleFileSizeInMB: 30,
			maxUploadSizeInMB: 300,
			acceptedFormats: ["pdf", "docx", "xlsx"],
		},
		{
			id: "hasAutomation",
			text: "Has any automation been developed for performing Rollback Automations?",
			required: true,
			type: "radio",
			cardTitle: "Automation Status",
			cardIcon: "Terminal",
			options: [
				{
					value: "yes",
					label: "Yes",
					description: "Fully automated",
					color: "green",
				},
				{
					value: "partial",
					label: "Partial",
					description: "Some steps automated",
					color: "blue",
				},
				{
					value: "no",
					label: "No",
					description: "Completely manual",
					color: "red",
				},
			],
			conditionalQuestions: {
				yes: [
					"automatedStepsCount",
					"uploadAutomationDocs",
					"minutesCount",
					"automationPayload",
					"validationMechanisms",
				],
				partial: [
					"automatedStepsCount",
					"uploadAutomationDocs",
					"validationMechanisms",
				],
			},
		},
		{
			id: "automatedStepsCount",
			text: "Please provide the total number of steps that are automated.",
			required: true,
			type: "number",
			icon: "Activity",
			unit: "steps",
			placeholder: "# of Steps",
			rows: 2,
			hidden: true,
		},
		{
			id: "uploadAutomationDocs",
			text: "If you have a separate MOP for automation please upload here. MOPs must be uploaded together; incremental updates are not supported.",
			required: false,
			type: "file",
			maxFiles: 10,
			maxSingleFileSizeInMB: 30,
			maxUploadSizeInMB: 300,
			acceptedFormats: ["pdf", "docx", "xlsx"],
			hidden: true,
		},
		{
			id: "minutesCount",
			text: "How many minutes does it take to complete the automated process?",
			required: false,
			type: "number",
			placeholder: "Enter time",
			description: "Average time to complete all Rollback steps manually",
			icon: "Clock",
			unit: "minutes",
			hidden: true,
		},
		{
			id: "automationPayload",
			text: "Is there automation to generate payloads required for above automations?",
			required: false,
			type: "radio",
			options: [
				{ value: "yes", label: "Yes" },
				{ value: "no", label: "No" },
			],
			hidden: true,
		},
		{
			id: "validationMechanisms",
			text: "What mechanisms do you use to determine whether the Rollback Automation steps were successful or failed?",
			required: true,
			type: "checkbox",
			options: [
				{ value: "health-checks", label: "Automated Health Checks" },
				{ value: "service-status", label: "Service Status Checks" },
				{ value: "database", label: "Database Validation" },
				{ value: "e2e", label: "E2E Testing" },
				{ value: "dashboards", label: "Monitoring Dashboards" },
				{ value: "logs", label: "Log Analysis" },
				{ value: "other", label: "Other" },
			],
			conditionalQuestions: {
				other: ["otherMechanism"],
			},
			hidden: true,
		},
		{
			id: "otherMechanism",
			text: "Please specify other mechanisms",
			required: true,
			type: "text",
			placeholder: "Please specify other mechanisms",
			hidden: true,
		},
		{
			id: "challenges",
			text: "Are there any challenges in performing Rollback Automations?",
			required: false,
			type: "textarea",
			cardTitle: "Challenges and Improvements",
			cardIcon: "HelpCircle",
			placeholder:
				"Please describe any challenges or obstacles you face when performing Rollback Automations",
			rows: 4,
			maxLength: 500,
			description:
				"Include any technical issues, resource constraints, or process bottlenecks",
			highlight: "Important",
		},
		{
			id: "improvements",
			text: "What suggestions or ideas do you have to improve the way Rollback Automation steps is being done for your NF?",
			required: false,
			type: "textarea",
			cardTitle: "Challenges and Improvements",
			placeholder: "Please share your ideas for improvement",
			rows: 4,
			maxLength: 500,
			description:
				"Consider automation, process efficiency, and better monitoring solutions",
		},
	],
	...commonSubmitValidation,
};

// Assurance Schema
export const assuranceSchema = {
	sectionName: "assurance",
	sectionTitle: "Assurance",
	sectionIcon: "Gauge",
	sectionColor: "indigo",
	sectionDescription:
		"Opportunities for open-loop and closed-loop assurance automation",
	questions: [
		{
			id: "configImpact",
			text: "Are there config changes that might impact other NFs and therefore require validations?",
			required: true,
			type: "textarea",
			cardTitle: "Configuration Impact",
			cardIcon: "AlertCircle",
			placeholder: "Please enter your response",
			rows: 3,
			highlight: "Critical",
		},
		{
			id: "automationOpportunities",
			text: "Are there any closed-loop or open-loop opportunities that can help operations team react to / resolve the issues affecting our customers, faster?",
			required: false,
			type: "textarea",
			cardTitle: "Automation Opportunities",
			cardIcon: "Gauge",
			placeholder: "Please enter your response",
			rows: 4,
			description:
				"Consider monitoring, automatic scaling, auto-remediation, and other operational automations",
		},
	],
	...commonSubmitValidation,
};

// Geo-Redundant/N+K Schema
export const geoRedundantSchema = {
	sectionName: "georedundant",
	sectionTitle: "Geo-Redundant/N+K",
	sectionIcon: "Map",
	sectionColor: "cyan",
	sectionDescription:
		"Procedures for configuring NF to support geo-redundancy and fault tolerance",
	questions: [
		{
			id: "hasMOPs",
			text: "Does your NF have MOPs available for performing Geo-redundancy? If so, please upload the MOPs in the next question. These can be vendor-provided and/or Verizon-created MOPs.",
			required: true,
			type: "radio",
			cardTitle: "MOP Availability",
			cardIcon: "FileCheck",
			options: [
				{ value: "yes", label: "Yes" },
				{ value: "no", label: "No" },
			],
			conditionalQuestions: {
				yes: ["uploadMOPs"],
			},
		},
		{
			id: "uploadMOPs",
			text: "Please upload the MOPs for Geo-redundancy. MOPs must be uploaded together; incremental updates are not supported.",
			required: true,
			type: "file",
			maxFiles: 10,
			maxSingleFileSizeInMB: 30,
			maxUploadSizeInMB: 300,
			acceptedFormats: ["pdf", "docx", "xlsx"],
			hidden: true,
		},
		{
			id: "stepsCount",
			text: "How many steps are involved in the Geo-redundancy?",
			required: true,
			type: "number",
			cardTitle: "Process Details",
			cardIcon: "Clock",
			placeholder: "Enter the number of steps",
			icon: "Activity",
			unit: "steps",
			description:
				"Enter the total number of discrete steps in the geo-redundancy process",
		},
		{
			id: "minutesCount",
			text: "How many minutes does it take to complete the manual process?",
			required: false,
			type: "number",
			placeholder: "Enter time",
			description:
				"How many minutes does it take to complete the manual process?",
			icon: "Clock",
			unit: "minutes",
		},
		{
			id: "uploadStepsDoc",
			text: "What are the steps involved in the Geo-redundancy? Please document and upload here. MOPs must be uploaded together; incremental updates are not supported.",
			required: false,
			type: "file",
			maxFiles: 10,
			maxSingleFileSizeInMB: 30,
			maxUploadSizeInMB: 300,
			acceptedFormats: ["pdf", "docx", "xlsx"],
		},
		{
			id: "hasAutomation",
			text: "Has any automation been developed for performing Geo-redundancy?",
			required: true,
			type: "radio",
			cardTitle: "Automation Status",
			cardIcon: "Terminal",
			options: [
				{
					value: "yes",
					label: "Yes",
					description: "Fully automated",
					color: "green",
				},
				{
					value: "partial",
					label: "Partial",
					description: "Some steps automated",
					color: "blue",
				},
				{
					value: "no",
					label: "No",
					description: "Completely manual",
					color: "red",
				},
			],
			conditionalQuestions: {
				yes: [
					"automatedStepsCount",
					"uploadAutomationDocs",
					"minutesCountAutomated",
					"automationPayload",
					"validationMechanisms",
				],
				partial: [
					"automatedStepsCount",
					"uploadAutomationDocs",
					"validationMechanisms",
				],
			},
		},
		{
			id: "automatedStepsCount",
			text: "Please provide the total number of steps that are automated.",
			required: true,
			type: "number",
			icon: "Activity",
			unit: "steps",
			placeholder: "# of Steps",
			rows: 2,
			hidden: true,
		},
		{
			id: "uploadAutomationDocs",
			text: "If you have a separate MOP for automation please upload here. MOPs must be uploaded together; incremental updates are not supported.",
			required: false,
			type: "file",
			maxFiles: 10,
			maxSingleFileSizeInMB: 30,
			maxUploadSizeInMB: 300,
			acceptedFormats: ["pdf", "docx", "xlsx"],
			hidden: true,
		},
		{
			id: "minutesCountAutomated",
			text: "How many minutes does it take to complete the automated process?",
			required: false,
			type: "number",
			placeholder: "Enter time",
			description: "Average time to complete all steps",
			icon: "Clock",
			unit: "minutes",
			hidden: true,
		},
		{
			id: "automationPayload",
			text: "Is there automation to generate payloads required for above automations?",
			required: false,
			type: "radio",
			options: [
				{ value: "yes", label: "Yes" },
				{ value: "no", label: "No" },
			],
			hidden: true,
		},
		{
			id: "validationMechanisms",
			text: "What mechanisms do you use to determine whether the Geo-Redundant/N+K steps were successful or failed?",
			required: true,
			type: "checkbox",
			options: [
				{ value: "health-checks", label: "Automated Health Checks" },
				{ value: "service-status", label: "Service Status Checks" },
				{ value: "database", label: "Database Validation" },
				{ value: "e2e", label: "E2E Testing" },
				{ value: "dashboards", label: "Monitoring Dashboards" },
				{ value: "logs", label: "Log Analysis" },
				{ value: "other", label: "Other" },
			],
			conditionalQuestions: {
				other: ["otherMechanism"],
			},
			hidden: true,
		},
		{
			id: "otherMechanism",
			text: "Please specify other mechanisms",
			required: true,
			type: "text",
			placeholder: "Please specify other mechanisms",
			hidden: true,
		},
		{
			id: "challenges",
			text: "Are there any challenges in performing Geo-redundancy?",
			required: false,
			type: "textarea",
			cardTitle: "Challenges and Improvements",
			cardIcon: "HelpCircle",
			placeholder:
				"Please describe any challenges or obstacles you face when performing Geo-redundancy",
			rows: 4,
			maxLength: 500,
			description:
				"Include any technical issues, resource constraints, or process bottlenecks",
			highlight: "Important",
		},
		{
			id: "improvements",
			text: "What suggestions or ideas do you have to improve the way Geo-redundancy steps is being done for your NF?",
			required: false,
			type: "textarea",
			cardTitle: "Challenges and Improvements",
			placeholder: "Please share your ideas for improvement",
			rows: 4,
			maxLength: 500,
			description:
				"Consider automation, process efficiency, and better monitoring solutions",
		},
	],
	...commonSubmitValidation,
};

// Disaster Recovery Schema
export const disasterRecoverySchema = {
	sectionName: "disasterrecovery",
	sectionTitle: "Disaster Recovery",
	sectionIcon: "LifeBuoy",
	sectionColor: "red",
	sectionDescription: "Procedures for recovering the NF after a disaster",
	questions: [
		{
			id: "hasMOPs",
			text: "Does your NF have MOPs available for performing Disaster Recovery? If so, please upload the MOPs in the next question. These can be vendor-provided and/or Verizon-created MOPs.",
			required: true,
			type: "radio",
			cardTitle: "MOP Availability",
			cardIcon: "FileCheck",
			options: [
				{ value: "yes", label: "Yes" },
				{ value: "no", label: "No" },
			],
			conditionalQuestions: {
				yes: ["uploadMOPs"],
			},
		},
		{
			id: "undocumentedSteps",
			text: "Do you have any disater recovery steps that are performed that are not part of any MOPs? If so, please provide the list of steps with details - actions being performed,  how they are performed, and the expected results; along with any remediation procedures if the distastory recovery fails.",
			required: false,
			cardTitle: "MOP Availability",
			cardIcon: "Terminal",
			type: "textarea",
			placeholder: "Your steps here:",
			rows: 4,
		},

		{
			id: "uploadMOPs",
			text: "Please upload the MOPs for Disaster Recovery. MOPs must be uploaded together; incremental updates are not supported.",
			required: true,
			type: "file",
			maxFiles: 10,
			maxSingleFileSizeInMB: 30,
			maxUploadSizeInMB: 300,
			acceptedFormats: ["pdf", "docx", "xlsx"],
			hidden: true,
		},
		{
			id: "stepsCount",
			text: "How many steps are involved in the Disaster Recovery?",
			required: true,
			type: "number",
			cardTitle: "Process Details",
			cardIcon: "Clock",
			placeholder: "Enter the number of steps",
			icon: "Activity",
			unit: "steps",
			description:
				"Enter the total number of discrete steps in the disaster recovery process",
		},
		{
			id: "uploadStepsDoc",
			text: "What are the steps involved in the Disaster Recovery? Please document and upload here. MOPs must be uploaded together; incremental updates are not supported.",
			required: false,
			type: "file",
			maxFiles: 10,
			maxSingleFileSizeInMB: 30,
			maxUploadSizeInMB: 300,
			acceptedFormats: ["pdf", "docx", "xlsx"],
		},
		{
			id: "hasAutomation",
			text: "Has any automation been developed for performing Disaster Recovery?",
			required: true,
			type: "radio",
			cardTitle: "Automation Status",
			cardIcon: "Terminal",
			options: [
				{
					value: "yes",
					label: "Yes",
					description: "Fully automated",
					color: "green",
				},
				{
					value: "partial",
					label: "Partial",
					description: "Some steps automated",
					color: "blue",
				},
				{
					value: "no",
					label: "No",
					description: "Completely manual",
					color: "red",
				},
			],
			conditionalQuestions: {
				yes: [
					"automatedStepsCount",
					"minutesCount",
					"automationPayload",
					"validationMechanisms",
				],
				partial: ["automatedStepsCount", "validationMechanisms"],
			},
		},
		{
			id: "automatedStepsCount",
			text: "Please provide the total number of steps that are automated.",
			required: true,
			type: "number",
			icon: "Activity",
			unit: "steps",
			placeholder: "# of Steps",
			rows: 2,
			hidden: true,
		},
		{
			id: "minutesCount",
			text: "How many minutes does it take to complete the automated process?",
			required: false,
			type: "number",
			placeholder: "Enter time",
			description: "Average time to complete all Rollback steps manually",
			icon: "Clock",
			unit: "minutes",
			hidden: true,
		},
		{
			id: "automationPayload",
			text: "Is there automation to generate payloads required for above automations?",
			required: false,
			type: "radio",
			options: [
				{ value: "yes", label: "Yes" },
				{ value: "no", label: "No" },
			],
			hidden: true,
		},
		{
			id: "validationMechanisms",
			text: "What mechanisms do you use to determine whether the Disaster Recovery steps were successful or failed?",
			required: true,
			type: "checkbox",
			options: [
				{ value: "health-checks", label: "Automated Health Checks" },
				{ value: "service-status", label: "Service Status Checks" },
				{ value: "database", label: "Database Validation" },
				{ value: "e2e", label: "E2E Testing" },
				{ value: "dashboards", label: "Monitoring Dashboards" },
				{ value: "logs", label: "Log Analysis" },
				{ value: "other", label: "Other" },
			],
			conditionalQuestions: {
				other: ["otherMechanism"],
			},
			hidden: true,
		},
		{
			id: "otherMechanism",
			text: "Please specify other mechanisms",
			required: true,
			type: "text",
			placeholder: "Please specify other mechanisms",
			hidden: true,
		},
		{
			id: "challenges",
			text: "Are there any challenges in performing Disaster Recovery?",
			required: false,
			type: "textarea",
			cardTitle: "Challenges and Improvements",
			cardIcon: "HelpCircle",
			placeholder:
				"Please describe any challenges or obstacles you face when performing Disaster Recovery",
			rows: 4,
			maxLength: 500,
			description:
				"Include any technical issues, resource constraints, or process bottlenecks",
			highlight: "Important",
		},
		{
			id: "improvements",
			text: "What suggestions or ideas do you have to improve the way Disaster Recovery steps is being done for your NF?",
			required: false,
			type: "textarea",
			cardTitle: "Challenges and Improvements",
			placeholder: "Please share your ideas for improvement",
			rows: 4,
			maxLength: 500,
			description:
				"Consider automation, process efficiency, and better monitoring solutions",
		},
	],
	...commonSubmitValidation,
};
// Section information array - defines all available sections and their metadata
export const sectionInfo = [
	{
		id: 0,
		title: "Health Check",
		description: "Routine tasks performed to ensure the NF is healthy.",
		icon: "Activity",
		color: "blue",
	},
	{
		id: 1,
		title: "Deployment - Pre-Install Steps",
		description: "Tasks performed before installing the NF software",
		icon: "FileCheck",
		color: "emerald",
	},
	{
		id: 2,
		title: "Deployment - Install Steps",
		description: "Tasks performed to install NF software",
		icon: "HardDrive",
		color: "emerald",
	},
	{
		id: 3,
		title: "Deployment - Post-Install Steps",
		description: "Tasks performed to configure the NF (Day-x)",
		icon: "CheckCircle2",
		color: "emerald",
	},
	{
		id: 4,
		title: "Upgrade - Pre-Checks Steps",
		description: "Tasks performed before upgrading the NF software.",
		icon: "FileCheck",
		color: "purple",
	},
	{
		id: 5,
		title: "Upgrade - Upgrade Steps",
		description: "Tasks performed to upgrade the NF software version.",
		icon: "Zap",
		color: "purple",
	},
	{
		id: 6,
		title: "Upgrade - Post-Checks Steps",
		description: "Tasks performed after upgrading the NF software version",
		icon: "CheckCircle2",
		color: "purple",
	},
	{
		id: 7,
		title: "Config Audit",
		description:
			"Tasks performed to ensure the NF configuration aligns with the baseline or golden configuration",
		icon: "FileText",
		color: "amber",
	},
	{
		id: 8,
		title: "Config Change",
		description: "Procedures for modifying NF parameter values",
		icon: "Settings",
		color: "amber",
	},
	{
		id: 9,
		title: "Rollback Automations",
		description:
			"Tasks performed to revert the NF to a previous software or configuration version",
		icon: "RefreshCw",
		color: "red",
	},
	{
		id: 10,
		title: "Assurance",
		description:
			"Opportunities for open-loop and closed-loop assurance automation",
		icon: "Gauge",
		color: "indigo",
	},
	{
		id: 11,
		title: "Geo-Redundant/N+K",
		description:
			"Procedures for configuring NF to support geo-redundancy and fault tolerance",
		icon: "Map",
		color: "cyan",
	},
	{
		id: 12,
		title: "Disaster Recovery",
		description: "Procedures for recovering the NF after a disaster",
		icon: "LifeBuoy",
		color: "red",
	},
];

// Initialize schema map with defined schemas
const schemaMap = {
	0: healthCheckSchema,
	1: preInstallSchema,
	2: installSchema,
	3: postInstallSchema,
	4: preUpgradeSchema,
	5: upgradeSchema,
	6: postUpgradeSchema,
	7: configAuditSchema,
	8: configChangeSchema,
	9: rollbackSchema,
	10: assuranceSchema,
	11: geoRedundantSchema,
	12: disasterRecoverySchema,
};

/**
 * Generates placeholder schemas for sections without detailed definitions
 * @returns {Object} Map of all section schemas indexed by section ID
 */
export const loadAllSchemas = () => {
	// Clone the schemaMap to avoid modifying the original
	const allSchemas = { ...schemaMap };

	// Generate placeholder schemas for sections without detailed definitions
	for (let i = 0; i <= 12; i++) {
		if (!allSchemas[i]) {
			const section = sectionInfo[i];

			// Create a placeholder schema
			allSchemas[i] = {
				sectionName: section.title
					.toLowerCase()
					.replace(/\s+/g, "")
					.replace(/-/g, ""),
				sectionTitle: section.title,
				sectionIcon: section.icon,
				sectionColor: section.color,
				sectionDescription: section.description,
				questions: [
					{
						id: "placeholder",
						text: `This is a placeholder for the ${section.title} section. This section would follow the same pattern as the other forms with similar questions adapted for this specific procedure.`,
						required: false,
						type: "info",
						cardTitle: "Section Information",
						cardIcon: section.icon,
					},
				],
			};
		}
	}

	return allSchemas;
};

// Get icon component helper function
export const getIconComponent = (iconName, size = 20) => {
	const iconMap = {
		Activity,
		AlertCircle,
		CheckCircle2,
		Clock,
		Database,
		FileCheck,
		FileText,
		Gauge,
		HardDrive,
		HelpCircle,
		LifeBuoy,
		Map,
		RefreshCw,
		Settings,
		Terminal,
		Upload,
		Zap,
		BarChart2,
	};

	const IconComponent = iconMap[iconName];
	return IconComponent ? <IconComponent size={size} /> : null;
};

// Helper function to get color class based on section
export const getSectionColorClass = (section, type) => {
	const colorMap = {
		blue: {
			bg: "bg-blue-100",
			bgDark: "bg-blue-600",
			text: "text-blue-800",
			textDark: "text-blue-600",
			border: "border-blue-200",
			hover: "hover:bg-blue-50",
			gradient: "from-blue-50 to-blue-100",
			buttonGradient:
				"from-blue-600 to-blue-800 hover:from-blue-700 hover:to-blue-900",
		},
		emerald: {
			bg: "bg-emerald-100",
			bgDark: "bg-emerald-600",
			text: "text-emerald-800",
			textDark: "text-emerald-600",
			border: "border-emerald-200",
			hover: "hover:bg-emerald-50",
			gradient: "from-emerald-50 to-emerald-100",
			buttonGradient:
				"from-emerald-600 to-emerald-800 hover:from-emerald-700 hover:to-emerald-900",
		},
		purple: {
			bg: "bg-purple-100",
			bgDark: "bg-purple-600",
			text: "text-purple-800",
			textDark: "text-purple-600",
			border: "border-purple-200",
			hover: "hover:bg-purple-50",
			gradient: "from-purple-50 to-purple-100",
			buttonGradient:
				"from-purple-600 to-purple-800 hover:from-purple-700 hover:to-purple-900",
		},
		amber: {
			bg: "bg-amber-100",
			bgDark: "bg-amber-600",
			text: "text-amber-800",
			textDark: "text-amber-600",
			border: "border-amber-200",
			hover: "hover:bg-amber-50",
			gradient: "from-amber-50 to-amber-100",
			buttonGradient:
				"from-amber-600 to-amber-800 hover:from-amber-700 hover:to-amber-900",
		},
		red: {
			bg: "bg-red-100",
			bgDark: "bg-red-600",
			text: "text-red-800",
			textDark: "text-red-600",
			border: "border-red-200",
			hover: "hover:bg-red-50",
			gradient: "from-red-50 to-red-100",
			buttonGradient:
				"from-red-600 to-red-800 hover:from-red-700 hover:to-red-900",
		},
		indigo: {
			bg: "bg-indigo-100",
			bgDark: "bg-indigo-600",
			text: "text-indigo-800",
			textDark: "text-indigo-600",
			border: "border-indigo-200",
			hover: "hover:bg-indigo-50",
			gradient: "from-indigo-50 to-indigo-100",
			buttonGradient:
				"from-indigo-600 to-indigo-800 hover:from-indigo-700 hover:to-indigo-900",
		},
		cyan: {
			bg: "bg-cyan-100",
			bgDark: "bg-cyan-600",
			text: "text-cyan-800",
			textDark: "text-cyan-600",
			border: "border-cyan-200",
			hover: "hover:bg-cyan-50",
			gradient: "from-cyan-50 to-cyan-100",
			buttonGradient:
				"from-cyan-600 to-cyan-800 hover:from-cyan-700 hover:to-cyan-900",
		},
	};

	return colorMap[section.color][type];
};

// Export the full schema map
export default loadAllSchemas();
